"use client";
import Button from "@/components/atoms/button/Button";
import SelectBox from "@/components/atoms/selectBox/Select";
import TagButton from "@/components/atoms/tagButton/TagButton";
import ToasterMsg from "@/components/atoms/toastMsg/Toaster";
import Box from "@mui/material/Box";
import Grid from "@mui/material/Grid";
import Typography from "@mui/material/Typography";
import { useEffect } from "react";
import { SubmitHandler, useForm } from "react-hook-form";
import styles from "./addressForm.module.scss";

type Areas = {
  [key: string]: string[];
};

type formFields = {
  fullName: string;
  phone: number;
  division: string;
  city: string;
  area: string;
  address: string;
  landmark: string;
  deliveryOption: string;
};

interface AddressFormProps {
  handleAction: (data: formFields) => void;
}
const AddressForm: React.FC<AddressFormProps> = ({ handleAction }) => {
  const {
    register,
    handleSubmit,
    formState: { errors },
    setValue,
    getValues,
    watch,
  } = useForm<formFields>();

  const handleAddressData: SubmitHandler<formFields> = (data: formFields) => {
    handleAction(data);
  };

  const divisions = [
    {
      name: "Barishal",
      cities: [
        "Barguna",
        "Barisal-Agailjhara",
        "Barisal-Babuganj",
        "Barisal-Bakerganj",
        "Barisal-Gouranadi",
        "Barisal-Hizla",
        "Barisal-Mehendiganj",
        "Barisal-Muladi",
        "Barisal-Town",
        "Barisal-Uzipur",
        "Bhola",
        "Jhalokati",
        "Patuakhali",
        "Pirojpur",
      ],
    },
    {
      name: "Chattogram",
      cities: [
        "Bandarban",
        "Brahmanbaria",
        "Brahmanbaria-Kasba",
        "Brahmanbaria-Nabinagar",
        "Brahmanbaria-Sarail",
        "Chandpur-Faridganj",
        "Chandpur-Hajiganj",
        "Chandpur-Hayemchar",
        "Chandpur-Kachua",
        "Chandpur-Matlab",
        "Chandpur Sadar",
        "Chandpur-Shahrasti",
        "Chattogram-Boalkhali",
        "Chattogram-Anowara",
        "Chattogram-Banshkhali",
        "Chattogram-Chandanaish",
        "Chattogram-Fatikchhari",
        "Chattogram-Hathazari",
        "Chattogram-Lohagara",
        "Chattogram-Mirsharai",
        "Chattogram-Patiya",
        "Chattogram-Rangunia",
        "Chattogram-Raozan",
        "Chattogram Sadar",
        "Chattogram-Sandwip",
        "Chattogram-Satkania",
        "Chattogram-Sitakunda",
        "Comilla-Barura",
        "Comilla-Brahmanpara",
        "Comilla-Burichang",
        "Comilla-Chandina",
        "Comilla-Choddagram",
        "Comilla-Daudkhandi",
        "Comilla-Davidhar",
        "Comilla-Homna",
        "Comilla-Laksam",
        "Comilla-Lalmai",
        "Comilla-Langalkot",
        "Comilla-Meghna",
        "Comilla-Monohorganj",
        "Comilla-Muradnagar",
        "Comilla Sadar",
        "Cox's Bazar-Chakaria",
        "Cox's Bazar-Eidgaon",
        "Cox's Bazar-Kutubdia",
        "Cox's Bazar-Moheskhali",
        "Cox's Bazar-Ramu",
        "Cox's Bazar Sadar",
        "Cox's Bazar-Teknaf",
        "Cox's Bazar-Ukhia",
        "Feni-Chhagalnaia",
        "Feni-Daganbhuiyan",
        "Feni-Pashurampur",
        "Feni Sadar",
        "Feni-Sonagazi",
        "Hatiya",
        "Khagrachhari-Dighinala",
        "Khagrachhari-Laxmichhari",
        "Khagrachhari-ManikChhari",
        "Khagrachhari-Matiranga",
        "Khagrachhari-Panchhari",
        "Khagrachhari-Ramghar",
        "Lakshmipur",
        "Lakshmipur-Raipur",
        "Lakshmipur-Ramganj",
        "Lakshmipur-Ramgati",
        "Lakshmipur-Raypur",
        "Noakhali",
        "Noakhali-Basurhat",
        "Noakhali-Begumganj",
        "Noakhali-Chatkhil",
        "Noakhali-Senbag",
        "Rangamati Barkal",
        "Rangamati-Bilaichhari",
        "Rangamati-Juraichhari",
        "Rangamati-Kaptai",
        "Rangamati-Kawkhali",
        "Rangamati-Langadu",
        "Rangamati Marishya",
        "Rangamati-Naniachhar",
        "Rangamati-Rajsthali",
        "Rangamati Town",
      ],
    },
    {
      name: "Dhaka",
      cities: [
        "Dhaka-North",
        "Dhaka-South",
        "Faridpur",
        "Gazipur",
        "Gopalganj",
        "Keraniganj-Dhaka",
        "Kishoreganj",
        "Madaripur",
        "Manikganj-Shibloya",
        "Manikganj-Singair",
        "Manikganj-Town",
        "Munshiganj-Gajaria",
        "Munshiganj-Lohajong",
        "Munshiganj-Sirajdhikhan",
        "Munshiganj-Town",
        "Narayanganj",
        "Narsingdi",
        "Nawabganj",
        "Rajbari-Baliakandi",
        "Rajbari-Pangsha",
        "Rajbari-Town",
        "Savar",
        "Shariatpur-Naria",
        "Shariatpur-Town",
        "Tangail-Basail",
        "Tangail-Bhuapur",
        "Tangail-Deldur",
        "Tangail-Dhanbari",
        "Tangail-Ghatail",
        "Tangail-Gopalpur",
        "Tangail-Kalihati",
        "Tangail-Madhupur",
        "Tangail-Mirzapur",
        "Tangail-Nagarpur",
        "Tangail-Sakhipur",
        "Tongi",
      ],
    },
    {
      name: "Khulna",
      cities: [
        "Bagerhat",
        "Chuadanga",
        "Jessore",
        "Jhenaidaha",
        "Khulna-Aliapur",
        "Khulna-Amadee",
        "Khulna-Batiaghat",
        "Khulna-Chalna Bazar",
        "Khulna-Digalia",
        "Khulna-Dumuria",
        "Khulna-Paikgachha",
        "Khulna-Terokhada",
        "Khulna-Town",
        "Kushtia",
        "Magura",
        "Meherpur",
        "Narail",
        "Satkhira",
      ],
    },
    {
      name: "Mymensingh",
      cities: [
        "Jamalpur-Dewangonj",
        "Jamalpur-Islampur",
        "Jamalpur-Madarganj",
        "Jamalpur-Malandah",
        "Jamalpur-Shorishbari",
        "Jamalpur-Town",
        "Mymensingh-Gaforgaon",
        "Mymensingh-Gouripur",
        "Mymensingh-Haluaghat",
        "Mymensingh-Isshwargonj",
        "Mymensingh-Muktagacha",
        "Mymensingh-Nandail",
        "Mymensingh-Phulpur",
        "Mymensingh-Town",
        "Mymensingh-Trishal",
        "Netrokona",
        "Sherpur",
      ],
    },
    {
      name: "Rajshahi",
      cities: [
        "Bogura",
        "Chapai Nawabganj",
        "Joypurhat",
        "Naogaon",
        "Natore",
        "Pabna",
        "Rajshahi",
        "Sirajganj",
      ],
    },
    {
      name: "Rangpur",
      cities: [
        "Dinajpur",
        "Gaibandha",
        "Kurigram",
        "Lalmonirhat",
        "Nilphamari",
        "Nilphamari-Saidpur",
        "Panchagarh",
        "Rangpur",
        "Thakurgaon",
      ],
    },
    {
      name: "Sylhet",
      cities: [
        "Habiganj",
        "Maulvi Bazar",
        "Sunamganj",
        "Sylhet-Balaganj",
        "Sylhet-Bianibazar",
        "Sylhet-Bishwanath",
        "Sylhet-Fenchuganj",
        "Sylhet-Goainhat",
        "Sylhet-Gopalganj",
        "Sylhet-Jakiganj",
        "Sylhet-Kanaighat",
        "Sylhet Sadar",
      ],
    },
  ];

  const areas: Areas = {
    Barguna: [
      "Barguna-Amtoli",
      "Barguna-Bamna",
      "Barguna Government College",
      "Barguna Sadar",
      "Barguna Taltali",
      "Barguna West Police Farry",
      "Betagi",
      "Darul Ulum",
      "Kakchira",
      "Nali Bandar",
      "Patharghata",
    ],
    "Barisal-Agailjhara": [
      "Agailjhara Bazar",
      "Agailjhara Sadar",
      "Gaila",
      "Paisarhat",
    ],
    "Barisal-Babuganj": [
      "Babuganj Sadar",
      "Barishal Cadet College",
      "Chandpasha",
      "Dehergoti",
      "Guthia",
      "Madhabpasha",
      "Nizamuddin College",
      "Rahamatpur",
      "Thakur Mallik",
    ],
    "Barisal-Bakerganj": [
      "Bakerganj Darial",
      "Charamandi",
      "Garuria",
      "Kalaskati",
      "Padri Shibpur",
      "Sahebganj",
    ],
    "Barisal-Gouranadi": [
      "Batajor",
      "Gouranadi Launch Ghat",
      "Gouranadi Sadar",
      "Kashemabad",
      "Mridha Market",
      "Tarki Bandar",
    ],
    "Barisal-Hizla": ["Barajalia Sadar", "Memania", "Osman Manjil"],
    "Barisal-Mehendiganj": [
      "Langutia",
      "Laskarpur",
      "Mehendiganj Sadar",
      "Ulania",
    ],
    "Barisal-Muladi": [
      "Bara Madhab rayer char",
      "Charkalekhan",
      "Kazirchar",
      "Muladi Sadar",
    ],
    "Barisal-Town": [
      "Barishal Kazipara",
      "Barishal Sadar",
      "Bibir Pukur",
      "Bukhainagar",
      "Chahutpur",
      "Jaguarhat",
      "Kashipur",
      "Kawnia",
      "Moth Baria",
    ],
    "Barisal-Uzipur": [
      "Dakuarhat",
      "Dhamura",
      "Jugirkanda",
      "Shikarpur",
      "Uzipur Bazar",
      "Uzipur Sadar",
      "Wazirpur Bazar",
    ],
    Bhola: [
      "Abhohawa Office Road",
      "Ali Nagar",
      "Bangla School Mor",
      "Bankar Hat",
      "Bhola Bapta",
      "Bhola Boys School Road",
      "Bhola Central Post Office",
      "Bhola Collage Road",
      "Bhola Girls Collage Road",
      "Bhola Notun Bazar",
      "Bhola Sadar",
      "Bhola Sadar Hospital Road",
      "Bhola UKil Para",
      "Borhanuddinn UPO",
      "Charfashion",
      "Char Kalmi",
      "Chornoyabad",
      "Chorshami",
      "Daurihat",
      "Dorga Road",
      "Doulatkhan",
      "Dularhat",
      "Gazaria",
      "Hajipur",
      "Hajirhat",
      "Hatshoshiganj",
      "Jamiralota",
      "Joynagar",
      "Kalibari Road",
      "Kalikhola Road",
      "Keramatganj",
      "Lalmohan UPO",
      "Mirzakalu",
      "Monpura",
      "Mostofa Kamal Bus Stand",
      "Nasir Mazi",
      "New Elisha Bus Stand",
      "Nobi Pur",
      "Old Elisha Bus Stand",
      "P.T.I Road",
      "Pouro Khathali",
      "Roton Pur",
      "Sodurchar",
      "Tazumuddin",
      "Western Para",
    ],
    Jhalokati: [
      "Alam Market",
      "Amtola Bazar",
      "Amua",
      "Amua Bazar",
      "Amua Zero Point",
      "Aorabunia Dokkhinpar Bazar",
      "Bablatola Bazar",
      "Baidarapur",
      "Banai Bazar",
      "Bashonda",
      "Baukathi",
      "Beerkathi",
      "Bhairabpasha",
      "Bhavanipur Launch Station",
      "Binapani Bazar",
      "Binoy Khathi",
      "Bisic Silponogori Jhalokhati",
      "Bot Tola Bazar",
      "C&B Bazar",
      "Centrer Hat",
      "Charukhan",
      "Dapdapia Launch Ghat",
      "Darul Habib Khanka Sharif Dapdapia Barishal",
      "Deulkati",
      "Dopdipia Fish Bazar",
      "Fokir Market",
      "Gabha",
      "Gabkhan",
      "Galua Bazar",
      "Gopalpur Pochchim Para",
      "Guachitra Bazar",
      "Guhuder Bazar",
      "Hodua Bazar",
      "Hodua Launch Terminal",
      "Islamia Bazar",
      "Jhalokati Sadar",
      "Kachua Ferry Terminal",
      "Kathalia",
      "Khejurtala Bazar",
      "Kirtipasha",
      "Kalokopa Bazar",
      "Kulkhathi Bazar",
      "Magar Bazar",
      "Mahtab Malta Bagan",
      "Manpasha",
      "Mohajon Bazar",
      "Mollar Hatt Bazar",
      "Morichbunia Bazar",
      "Mothbari",
      "Munsirabad Bazar Jhalokathi Shouljalia",
      "Nabagram",
      "Nalchhiti",
      "Nathullabadh",
      "Notun Hath Bazar Jhalokathi Ranapasha",
      "Noyarasta Bazar",
      "Panchagram Bazar",
      "Pingri",
      "Ponabalia Bazar",
      "Protap",
      "Rajapur",
      "Rajapur Jhalokatii",
      "Satani Bazar",
      "Shakherhat",
      "Shameer Hat",
      "Shekherhat",
      "Shoulajalia",
      "South Palot Launch Terminal",
      "Taltola Bazar",
      "Tekerhat Bazar",
      "Ukel Bazar",
      "Uttar Bikna",
      "Zahatola Bazar",
    ],
    Patuakhali: [
      "Auliapur",
      "Bagabandar",
      "Barabighai",
      "Bauphal",
      "Birpasha",
      "Char Montaz",
      "Dashmina",
      "Dumkee",
      "Galachipa",
      "Gazipur Bandar",
      "Hetalia Badhghat",
      "Jainkathi",
      "Kalaia",
      "Kalapara-Galachipa",
      "Kalishari",
      "Katpotti",
      "Khepupara",
      "Kuakata",
      "Lebukhali",
      "Lohalia",
      "Mahipur",
      "Marichbunia",
      "Mirjaganj Sarak",
      "Mitha Pukur Par",
      "Moukaran",
      "Mukul Cinema Hall",
      "Nobab Para",
      "Patuakhali Banani",
      "Patuakhali Jailkhana Road",
      "Patuakhali Medical College Hospital",
      "Patuakhali Notun Bazar",
      "Patuakhali Pourosova",
      "Patuakhali Puran Bazar",
      "Patuakhali Sadar",
      "Patuakhali Shilpokola Academy",
      "Rangabali",
      "Subidkhali",
    ],
    Pirojpur: [
      "Amla Para",
      "Banaripara",
      "Betmor Natun Hat",
      "Bhandaria",
      "Bolaka Club Road",
      "Bolassor Bridge",
      "Boro Mosjid",
      "C.I Para",
      "Chakhar",
      "Damudar Bridge",
      "Darus Sunnat",
      "Dhaoa",
      "Dokhin Shikar Pur",
      "Dopa Bara",
      "Duppasa",
      "Gulishakhali",
      "Hularhat",
      "Jalabari",
      "Jolagati",
      "Joykul",
      "Kanudashkathi",
      "Kaukhali",
      "Kaurikhara",
      "Keundia",
      "Masim Pur",
      "Matani Road",
      "Mathbaria",
      "Mohila College Road",
      "Muchi Para",
      "Nazirpur",
      "Nirer Goli",
      "Parerhat",
      "Pirojpur Adarsha Para",
      "Pirojpur Boropul",
      "Pirojpur Bot Tola",
      "Pirojpur College Road",
      "Pirojpur DC Office",
      "Pirojpur Judge Court",
      "Pirojpur Lged",
      "Pirojpur New Bus Stand",
      "Pirojpur P.T.I Road",
      "Pirojpur Palpara",
      "Pirojpur Police Line",
      "Pirojpur Police Station",
      "Pirojpur Post Office",
      "Pirojpur Pouro Shoshan",
      "Pirojpur Puran Pouroshova Road",
      "Pirojpur Sadar",
      "Pirojpur Sadar Hospital",
      "Pirojpur Sadar Thana",
      "Pirojpur Surgicare",
      "Pirojpur Town Club",
      "Pirojpur Ukil Para",
      "Rajar Hat",
      "Sheikh Para",
      "Shikha Office",
      "Shilarganj",
      "Sriramkathi",
      "Tiarkhali",
      "Tushkhali",
      "Yasinkhar Pol",
    ],
    Bandarban: [
      "Bandarban-Alikadam",
      "Bandarban-Balaghata",
      "Bandarban Sadar",
      "Naikhong",
      "Naikhongchari",
      "Roanchhari",
      "Ruma",
      "Thanchi",
      "Thanchi Lama",
    ],
    Brahmanbaria: [
      "Akhaura",
      "Akhaura Gangasagar",
      "Banchharampur",
      "Bijoynagar",
      "Bijoynagar-Harashpur",
      "Brahmanbaria Sadar",
      "Brahmanbaria Sadar Ashuganj",
      "Brahmanbaria Sadar Ashuganj Share",
      "Brahmanbaria Sadar-Bhadughar",
      "Brahmanbaria Sadar-Gokarna Ghat",
      "Brahmanbaria Sadar-Natai",
      "Brahmanbaria Sadar Poun",
      "Brahmanbaria Sadar Talshahar",
      "Nabinagar-Hujur Bari",
      "Nasirnagar",
      "Suhilpur",
    ],
    "Brahmanbaria-Kasba": [
      "Kasba Chandidar",
      "Kasba Chargachh",
      "Kasba Gopinathpur",
      "Kasba Kuti",
      "Kasba Sadar",
      "Kullapathar",
      "Madla",
    ],
    "Brahmanbaria-Nabinagar": [
      "Nabinagar Jibanganj",
      "Nabinagar Kaitala",
      "Nabinagar Laubfatehpur",
      "Nabinagar Rasullabad",
      "Nabinagar Ratanpur",
      "Nabinagar Sadar",
      "Nabinagar Salimganj",
      "Nabinagar Shahapur",
      "Nabinagar Shamgram",
      "Nasirnagar Fandauk",
    ],
    "Brahmanbaria-Sarail": [
      "Sarail Chandura",
      "Sarail Sadar",
      "Sarail Shahbajpur",
    ],
    "Chandpur-Faridganj": [
      "Faridganj Chandra",
      "Faridganj Gridkaliandia",
      "Faridganj Islampur Shah Isain",
      "Faridganj Rampurbazar",
      "Faridganj Rupsha",
      "Faridganj Sadar",
    ],
    "Chandpur-Hajiganj": ["Hajiganj Bolakhal", "Hajiganj Hajiganj"],
    "Chandpur-Hayemchar": ["Hayemchar Gandamara", "Hayemchar Sadar"],
    "Chandpur-Kachua": [
      "Bedpur",
      "Kachua Rahima Nagar",
      "Kachua Sadar",
      "Kachua Shachar",
    ],
    "Chandpur-Matlab": [
      "Amuakandi",
      "Dakkhin Doulotpur",
      "Dakkhin Narayanpur",
      "Matlab Mohanpur",
      "Matlab Sadar",
      "Matlab Uttar Amiyapur",
      "Matlab Uttar Upazila Parishad",
      "Noyanogor",
      "Sujatpur Bazar",
    ],
    "Chandpur Sadar": [
      "Chandpur Chowrasta",
      "Chandpur Sadar Baburhat",
      "Chandpur Sadar Puranbazar",
      "Chandpur Sadar Sahatali",
    ],
    "Chandpur-Shahrasti": [
      "Shahrasti Chotoshi",
      "Shahrasti Islamia Madrasha",
      "Shahrasti Khilabazar",
      "Shahrasti Pashchim Kherihar Al",
      "Shahrasti Sadar",
    ],
    "Chattogram-Boalkhali": [
      "Boalkhali Charandwip",
      "Boalkhali Iqbal Park",
      "Boalkhali Kadurkhal",
      "Boalkhali Kanungopara",
      "Boalkhali Sadar",
      "Boalkhali Sakpura",
      "Boalkhali Saroatoli",
    ],
    "Chattogram-Anowara": ["Anawara Battali", "Anawara Paroikora", "Chatory"],
    "Chattogram-Banshkhali": [
      "Haliapara",
      "Jaldi Banigram",
      "Jaldi Gunagari",
      "Jaldi Khan Bahadur",
      "Jaldi Sadar",
      "Kalamarchara",
      "Napora",
      "Panirchara",
    ],
    "Chattogram-Chandanaish": [
      "East Joara Barma",
      "East Joara Dohazari",
      "East Joara East Joara",
      "East Joara Gachbaria",
    ],
    "Chattogram-Fatikchhari": [
      "Fatichhari Maiz Vandar Sharif",
      "Fatikchhari Fatikchhari",
      "Fatikchhari Harualchhari",
      "Fatikchhari Najirhat",
      "Fatikchhari Nanupur",
      "Fatikchhari Narayanhat",
    ],
    "Chattogram-Hathazari": [
      "Hathazari Chitt.University",
      "Hathazari Fatahabad",
      "Hathazari Gorduara",
      "Hathazari Hathazari",
      "Hathazari Katirhat",
      "Hathazari Madrasa",
      "Hathazari Mirzapur",
      "Hathazari Nuralibari",
      "Hathazari Yunus Nagar",
    ],
    "Chattogram-Lohagara": [
      "Lohagara Chunti",
      "Lohagara Lohagara",
      "Lohagara Padua",
    ],
    "Chattogram-Mirsharai": [
      "Mirsharai Abutorab",
      "Mirsharai Azampur",
      "Mirsharai Bharawazhat",
      "Mirsharai Darrogahat",
      "Mirsharai Joarganj",
      "Mirsharai Korerhat",
      "Mirsharai Mirsharai",
      "Mirsharai Mohazanhat",
    ],
    "Chattogram-Patiya": ["Patiya Budhpara", "Patiya Sadar"],
    "Chattogram-Rangunia": [
      "Dakkhin Ghatchak",
      "Fakirkill",
      "Kadeer Nagar",
      "Murad Nagar",
      "Rangunia Dhamair",
      "Rangunia Sadar",
      "Sayad Bari",
      "Uttar Gatchak",
    ],
    "Chattogram-Raozan": [
      "Raozan B.I.T Post Office",
      "Raozan Beenajuri",
      "Raozan Dewanpur",
      "Raozan Fatepur",
      "Raozan Guzra Noapara",
      "Raozan jagannath Hat",
      "Raozan Kundeshwari",
      "Raozan Mohamuni",
      "Raozan Pouroshobha",
      "Rauzan Gahira",
    ],
    "Chattogram Sadar": [
      "Agrabad",
      "AK Khan",
      "Al- Amin Baria Madrasa",
      "Amin Jute Mills",
      "Anandabazar",
      "Bayezid Bostami",
      "Cepz",
      "Chandgaon",
      "Chattogram Airport",
      "Chattogram Bandar",
      "Chattogram Cantonment",
      "Chattogram Customs Acca",
      "Chattogram GPO",
      "Chattogram New Market",
      "Chattogram Politechnic Institute",
      "Chattogram Sailers Colony",
      "Chawkbazar",
      "Colonel Hat",
      "Combined Military Hospital (CMH)",
      "Dakkshin Pahartoli",
      "Double Mooring",
      "Firozshah",
      "GEC",
      "Jaldia Marine Academy",
      "Khulshi",
    ],
    "Chattogram-Sandwip": [
      "Sandwip Post Office",
      "Sandwip Shiberhat",
      "Sandwip Urirchar",
    ],
    "Chattogram-Satkania": [
      "Satkania Baitul Ijjat",
      "Satkania Bazalia",
      "Satkania Satkania",
    ],
    "Chattogram-Sitakunda": [
      "Sitakunda Barabkunda",
      "Sitakunda Baroidhala",
      "Sitakunda Bawashbaria",
      "Sitakunda Bhatiari",
      "Sitakunda Fouzdarhat",
      "Sitakunda Jafrabad",
      "Sitakunda Kumira",
      "Sitakunda Sitakunda",
    ],
    "Comilla-Barura": [
      "Barura Murdafarganj",
      "Barura Poyalgachha",
      "Barura Sadar",
    ],
    "Comilla-Brahmanpara": [
      "Bagra",
      "Brahmanpara Sadar",
      "Chandla",
      "Shashidal",
      "Shidlai",
    ],
    "Comilla-Burichang": [
      "Adbarpur",
      "Burichang Maynamoti bazar",
      "Burichang Sadar",
    ],
    "Comilla-Chandina": [
      "Chandina Chandia",
      "Chandina Madhaiabazar",
      "Raj Kalibari",
    ],
    "Comilla-Choddagram": [
      "Chouddagram Batisa",
      "Chouddagram Chiora",
      "Chouddagram Upazila Health Complex",
    ],
    "Comilla-Daudkandi": [
      "Daudkandi Dashpara",
      "Daudkandi Daudkandi",
      "Daudkandi Eliotganj",
      "Daudkandi Gouripur",
    ],
    "Comilla-Davidhar": [
      "Companiganj",
      "Davidhar Barashalghar",
      "Davidhar Davidhar",
      "Davidhar Dhamtee",
      "Davidhar Gangamandal",
    ],
    "Comilla-Homna": ["Akhandapur", "Homna Homna", "Hujurkandi", "Mohonpur"],
    "Comilla-Laksam": ["Gajimura", "Laksam Bipulasar", "Laksam Lakshamanpur"],
    "Comilla-Lalmai": ["Amratali", "Baghmara", "Lalmai Pahar", "Poranpur"],
    "Comilla-Langalkot": [
      "Langalkot Chhariabazar",
      "Langalkot Chilpara",
      "Langalkot Dhalua",
      "Langalkot Gunabati",
    ],
    "Comilla-Meghna": [
      "Boro Kanda",
      "Chandanpur",
      "Manikar Char",
      "Meghna Luter Char",
      "Rampur Bazar",
      "Titir Char",
      "Vaor Khola",
    ],
    "Comilla-Monohorganj": [
      "Hasnabad Bazar",
      "Lakkhanpur",
      "Lalchandpur",
      "Monohorganj Sadar",
      "Natherpetua",
      "Shikchail",
    ],
    "Comilla-Muradnagar": [
      "Muradnagar Bangra",
      "Muradnagar Companyganj",
      "Muradnagar Muradnagar",
      "Muradnagar Pantibazar",
      "Muradnagar Ramchandarpur",
      "Muradnagar Sonakanda",
    ],
    "Comilla Sadar": [
      "Badurtola",
      "Baro Para",
      "Comilla Housing",
      "Comilla Sadar Comilla Contonment",
      "Comilla Sadar Courtbari",
      "Comilla Sadar Halimanagar",
      "Comilla Sadar Suaganj",
      "Dharmopur",
      "Kandirpar",
      "Kaptan Bazar",
      "Paduar Bazar",
      "Shashongachha",
      "Tomsom Bridge",
    ],
    "Cox's Bazar-Chakaria": [
      "Chakaria Sadar",
      "Chiringga Badarkali",
      "Chiringga Chiringga S.O",
      "Chiringga Malumghat",
      "Chiringga Sadar",
      "Dulahazara",
      "Harbang",
      "Khutakhali Bazar",
    ],
    "Cox's Bazar-Eidgaon": ["Eidgaon Union Parishad", "Pokkhali"],
    "Cox's Bazar-Kutubdia": ["Dhurung", "Kutubdia Sadar", "Lemsikhali"],
    "Cox's Bazar-Moheskhali": ["Gorakghat", "Hoanok", "Matarbari"],
    "Cox's Bazar-Ramu": ["Ramu Sadar", "Sonaichari"],
    "Cox's Bazar Sadar": [
      "Baharchora",
      "Bazarghata",
      "Cox's Bazar Bus Terminal",
      "Holiday Mor",
      "Kolatoli",
      "Laldighi Par",
      "Link Road",
    ],
    "Cox's Bazar-Teknaf": ["Teknaf Hnila", "Teknaf Sadar", "Teknaf St.Martin"],
    "Cox's Bazar-Ukhia": ["Ukhia - Noapara", "Ukhia Sadar"],
    "Feni-Chhagalnaia": [
      "Amjad Hat",
      "Bangla Bazar Haripur",
      "Bondua Dolotpur",
      "Box Mahmud",
      "Chhagalnaia Daraga Hat",
      "Chhagalnaia Maharajganj",
      "Chhagalnaia Puabashimulia",
      "Chhagalnaia Sadar",
      "Kalbat Bottoli Bazar",
      "Killadighi",
      "Puraton Muhuriganj Bazar",
      "Rezumia Bazar",
      "Shantir Bazar",
    ],
    "Feni-Daganbhuiyan": [
      "Badher Gora",
      "Bhuiyanr Hat",
      "Char Hakdi",
      "Char Laxigonj",
      "Chowdhuri Hat",
      "Daganbhuiyan Chhilonia",
      "Daganbhuiyan Dudmukha",
      "Daganbhuiyan Rajapur",
      "Daganbhuiyan Upazila Parishad",
      "Khushipur",
      "Mowlana Ghat Ferry Terminal",
      "Purba Chandrapur",
      "Sebar Hat",
      "Sindurpur Bazar",
      "South Karimpur Dagonbhuiyan Feni",
      "South Neaz Pur",
      "Taltoli Bazar",
    ],
    "Feni-Pashurampur": [
      "Pashurampur Fulgazi",
      "Pashurampur Munshirhat",
      "Pashurampur Pashurampur",
      "Pashurampur Shuarbazar",
    ],
    "Feni Sadar": [
      "Amtoli Bazar",
      "Bhanga Takia Bazar Sharshadie",
      "Chhagalnaiya - Shuvapur",
      "Court Buliding",
      "Daganbhuiyan - Biroli Bazar Bridge",
      "Daud Pul",
      "Dharmapur Amin Bazar",
      "Feni Cadet College",
      "Feni Circuit House",
      "Feni Police Line",
      "Feni Polytechnic Institute",
      "Feni Sadar",
      "Feni Sadar Fazilpur",
      "Feni Sadar Hospital",
      "Feni Sadar Laskarhat",
      "Feni Stadium",
      "Feni TB Hospital",
      "Feni University",
      "Grand Trunk Road",
      "Grand Trunk Road Square",
      "Gunabati Railway Station",
      "Hazir Bazar Post Office",
      "Ja Academy",
      "Kalidaha- Laskarhat Rd",
      "Khaiyara The Head",
    ],
    "Feni-Sonagazi": [
      "Bakter Munshi Bazar",
      "Bara Ahmadpur",
      "Char Laxmiganj",
      "Miyar Bazar Post Office Maruar Char",
      "Motiganj",
      "Nababpur Bazar",
      "Nobi Ullah Bazar",
      "Olama Bazar",
      "Sombaria Bazar",
      "Sonagazi Ahmadpur",
      "Sonagazi Kazirhat",
      "Sonagazi Motiganj",
      "Sonagazi Sadar",
      "Sonagazi Upazila Office",
      "Sonapur Bazar",
      "Sundarpur Baligaon",
    ],
    Hatiya: ["Hatiya Afazia", "Hatiya Sadar", "Hatiya Tamoraddi"],
    Khagrachari: [
      "Dighinala - Babuchhara",
      "Dighinala - Baghaichari Mukh",
      "Dighinala - Boalkhali Bazar",
      "Dighinala - Buddhist Monastery",
      "Dighinala - Chatrachhara Ch Mohan Para",
      "Dighinala - Dighinala",
      "Dighinala - Duluchhari",
      "Dighinala - Gyanangkur Buddha Vihara",
      "Dighinala - Jogesh Ch Karbari Para",
      "Dighinala - Kabakhali Bazar",
      "Dighinala - Madhya Dhanpatar",
      "Dighinala - Purbo Hasin Sanadpur",
      "Dighinala - Sardangchhara",
      "Khagrachari Sadar - Ananta Master Para",
      "Khagrachari Sadar - Chengy Square",
      "Khagrachari Sadar - Islampur",
      "Khagrachari Sadar - Jamtoli",
      "Khagrachari Sadar - Khagrachari Sadar",
      "Khagrachari Sadar - Komalchari Hadmanpara Bazar",
      "Khagrachari Sadar - Madhupur Bazar",
      "Khagrachari Sadar - Mahajanpara",
      "Khagrachari Sadar - Narankhaya",
      "Khagrachari Sadar - Perachara",
      "Khagrachari Sadar - Shalbagan",
      "Khagrachari Sadar - Shanirvar",
    ],
    "Khagrachari-Dighinala": ["Diginala Sadar"],
    "Khagrachari-Laxmichhari": ["Laxmichhari Sadar"],
    "Khagrachari-Manikchhari": ["Manikchhari Sadar"],
    "Khagrachari-Matiranga": ["Baranala", "Matiranga Sadar", "Taindong"],
    "Khagrachari-Panchhari": ["Panchhari Sadar"],
    "Khagrachari-Ramghar": ["Pathachhara", "Ramghar Head Office"],
    Lakshmipur: [
      "Birahimpur Lakshmipur",
      "Charshai",
      "Jagannatpur",
      "Lakshmipur Sadar",
      "Lakshmipur Sadar Amani Lakshimpur",
      "Lakshmipur Sadar Chandraganj",
      "Lakshmipur Sadar Choupalli",
      "Lakshmipur Sadar Dalal Bazar",
      "Lakshmipur Sadar Duttapara",
      "Lakshmipur Sadar Keramatganj",
      "Lakshmipur Sadar Mandari",
      "Lakshmipur Sadar Rupchara",
    ],
    "Lakshmipur-Raipur": ["Keroa", "Raipur Sadar"],
    "Lakshmipur-Ramganj": [
      "Ramganj Alipur",
      "Ramganj Bazar",
      "Ramganj Dolta",
      "Ramganj Kanchanpur",
      "Ramganj Naagmud",
      "Ramganj Panpara",
    ],
    "Lakshmipur-Ramgati": [
      "Char Alexander",
      "Char Alexander Hajirghat",
      "Char Goshai",
      "Char Poragacha",
      "Char Wapda",
      "Kamalnagar Jomidar Hat Bazar",
      "Ramgoti Bazar",
    ],
    "Lakshmipur-Raypur": [
      "Raypur Bhuabari",
      "Raypur Haydarganj",
      "Raypur Khaser Hat",
      "Raypur Nagerdighirpar",
      "Raypur Rakhallia",
      "Raypur Sadar",
    ],
    Noakhali: [
      "Alayarpur",
      "Amishsha Para",
      "Andar Char",
      "Banglabazar",
      "Bangla Bazar",
      "Bashurhaat",
      "Binodpur",
      "Bishwanaath Bus Stop",
      "Bojra Bazar",
      "Boro Mosjid Mor",
      "Chaiyaani Bazar",
      "Chandraganj Bazar",
      "Char Elahi Bazar",
      "Char Jabbar",
      "Char Jublee",
      "Chatarpaiyaa",
      "Chatarpaiya Bazar",
      "Chatkil",
      "Chowmohani Chowrasta",
      "Church Of The Queen Of Lourdes",
      "Companiganj Noakhali",
      "Dotter Haat",
      "Ekhlashpur Bazar",
      "Eklashpur Bazar",
      "Gabua Bazar",
    ],
    "Noakhali-Basurhat": ["Basurhat Basur Hat", "Basurhat Charhajari"],
    "Noakhali-Begumganj": [
      "Begumganj Alaiarpur",
      "Begumganj Amisha Para",
      "Begumganj Banglabazar",
      "Begumganj Bazra",
      "Begumganj Bhabani Jibanpur",
      "Begumganj Choumohani",
      "Begumganj Dauti",
      "Begumganj Durgapur",
      "Begumganj Gopalpur",
      "Begumganj Jamidar Hat",
      "Begumganj Joyag",
      "Begumganj Joynarayanpur",
      "Begumganj Khalishpur",
      "Begumganj Maheshganj",
      "Begumganj Mir Owarishpur",
      "Begumganj Nadona",
      "Begumganj Nandiapara",
      "Begumganj Oachhekpur",
      "Begumganj Rajganj",
      "Begumganj Sadar",
      "Begumganj Sonaimuri",
      "Begumganj Tangirpar",
    ],
    "Noakhali-Chatkhil": [
      "Chatkhil Bansa Bazar",
      "Chatkhil Bodalcourt",
      "Chatkhil Dosh Gharia",
      "Chatkhil Karihati",
      "Chatkhil Khilpara",
      "Chatkhil Palla",
      "Chatkhil Rezzakpur",
      "Chatkhil Sadar",
      "Chatkhil Sahapur",
      "Chatkhil Sampara",
      "Chatkhil Shingbahura",
      "Chatkhil Solla",
    ],
    "Noakhali-Senbag": [
      "Senbag Beezbag",
      "Senbag Chatarpaia",
      "Senbag Kallyandi",
      "Senbag Kankirhat",
      "Senbag Sadar",
      "Senbag T.P. Lamua",
    ],
    "Rangamati Barkal": ["Barkal Bazar", "Barkal Sadar", "Panchagram"],
    "Rangamati-Bilaichhari": ["Bilaichhari Bilaichhari"],
    "Rangamati-Juraichhari": ["Jarachhari Jarachhari"],
    "Rangamati-Kaptai": [
      "Kaptai Chandraghona",
      "Kaptai Kaptai Project",
      "Kaptai Nuton Bazar",
      "Kaptai Sadar",
    ],
    "Rangamati-Kawkhali": ["Betbunia", "Kalampati"],
    "Rangamati-Langadu": ["Gulshakhali", "Langadu Sadar"],
    "Rangamati Marishya": ["Marishya Sadar"],
    "Rangamati-Naniachhar": ["Naniachhar Sadar"],
    "Rangamati-Rajsthali": ["Rajsthali Sadar"],
    "Rangamati Town": [
      "Kathaltoli",
      "Manikchari Rangamati",
      "Rangamati Sadar",
      "Vedvedi",
    ],
    "Dhaka-North": [
      "Bashundhara Block H",
      "Bashundhara Block I",
      "Bashundhara Bus Stand",
      "Baunia",
      "Bawlia Para",
      "Bawneabad Area",
      "Begunbari",
      "Bepari Bari",
      "Bhuyia Para",
      "Bishteki",
      "Bonolota",
      "Box Nagar",
      "CDH Shampan",
      "Chairman bari",
      "Chalabon",
      "Chalabon - Ark Hospital",
      "Chamurkhan",
      "Coca Cola Bus Stop",
      "Confidence Shopping Mall",
      "Dakkhinkhan Army Society",
      "Dakkhinkhan Azompur Brac Market",
      "Dakkhinkhan Chairman Para",
      "Dakkhinkhan Dewan Bari",
      "Dakkhinkhan Gono Koborshathan Road",
      "Dakkhinkhan Hatim Bag",
    ],
    "Dhaka-South": [
      "Barnamala School",
      "Basabo",
      "Bashabo Ohaba Colony",
      "Bashir uddin road",
      "Bashundhara City",
      "Basu Bazar Lane",
      "BDR Pilkhana",
      "Begum Bazar",
      "Bhagwati Banerjee Road",
      "Bhanga Press",
      "Bhojhari Saha Street",
      "Bijoy Nagar",
      "Central prison",
      "central public library",
      "Chamelibagh",
      "Chandi Charan Bose Street",
      "Chankharpul lane",
      "Chan Para",
      "ChanPara Zia Bagh",
      "Chawk Bazar",
      "Chittagong Road",
      "Chota Katra",
      "Circular Road",
      "Committee ganj",
      "Court House Street",
    ],
    Faridpur: [
      "Alfadanga",
      "Alipur",
      "Ambikapur",
      "Ambikapur Board Office",
      "Atrashi Sadarpur",
      "Bagat Bazar",
      "Baitul Aman Housing Society",
      "Baitulaman Politecni",
      "Bakhunda",
      "Bhanga",
      "Bhashanchar",
      "Bil Mamudpur",
      "Boalmari",
      "Bodorpur",
      "C&B Ghat",
      "Charbhadrasan Upazila Faridpur",
      "Char Hazigonj Bazar",
      "Chorkomlapur",
      "Chunaghata",
      "Dhuldi Bazar",
      "Dhuldi Railgate",
      "Durgapur Faridpur",
      "Engineering College",
      "Faridpur New Bus Stand",
      "Faridpur New Market",
    ],
    Gazipur: [
      "Ahmed Nagor Chowrasta - Shafipur",
      "Ansar Academy - Shafipur",
      "Apex Footwear Factory",
      "Apex Palli Bidyut",
      "Bagher Bazar",
      "Bahadurpur - Mowna Gazipur",
      "Bahawal College Chowrasta",
      "Barmi",
      "Bashon Thana Chowrasta",
      "Bason Sorok",
      "Bhawal Mirzapur",
      "Board Bazar",
      "Boardmill",
      "BRRI",
      "Brtc Chowrasta",
      "Chandra Baroipara",
      "Chandra Bus Stand",
      "Chandra Kobirpur",
      "Chatar Bazar",
      "Chowrasta Baypass",
      "Chowrasta Telipara",
      "Chowrasta Warelessgate",
      "Colombia Garments",
      "Deger Chala Road - Hariken",
      "Dhakkinan Joydebpur",
    ],
    Gopalganj: [
      "Arpara",
      "Gopalganj Dhaka Dakkhin",
      "Gopalganj Sadar",
      "Gopalganj Sadar Ulpur",
      "Gopinathpur",
      "Kashiani",
      "Kashiani Ramdia College",
      "Kotalipara",
      "Maksudpur",
      "Malenga",
      "Manikher",
      "Ratoil",
      "Tungipara",
      "Vatiapara",
    ],
    "Keraniganj-Dhaka": [
      "Abdullahpur Bazar",
      "Ati bazar",
      "Basundhara",
      "Dohar",
      "Ekuriya",
      "Hasnabad",
      "Kaligonj",
      "Keraniganj - Aganagar",
      "Keraniganj - Basta",
      "Keraniganj - Kalindi",
      "Keraniganj - Kholamora",
      "Keraniganj Sadar",
      "Keraniganj - Sakta",
      "Keraniganj - Suvadda",
      "Kodomtoly",
      "Konakhola",
      "Konda",
      "Ramerkanda",
      "Rohitpur",
      "Stand Bazar",
      "Zinzira",
    ],
    Kishoreganj: [
      "Boulai Bazar",
      "Chadurar Pool Putimari",
      "Chamraghat Bazar",
      "Chauddasata",
      "Dana Patuli",
      "Haruya",
      "Hossaindi Bazar",
      "Hossainpur Araibari",
      "Hossainpur Bazar",
      "Hossainpur Gobindapur",
      "Hossainpur Jirani",
      "Hossainpur Pumdi",
      "Hossainpur Sahedal",
      "Hossainpur Sidhla",
      "Hossenpur",
      "Itna Badla",
      "Itna Baribari",
      "Itna Chowganga",
      "Itna Dhanpur",
      "Itna Elongjuri",
      "Itna Gazipur",
      "Itna Joysiddi",
      "Itna Mrigha",
      "Itna Raituti",
      "Jalalpur Bazar",
      "Jamtola Bazar",
    ],
    Madaripur: [
      "Adampur",
      "Arial Khan Ferry Ghat",
      "Balairkandi",
      "Charmuguria",
      "Durgabordi",
      "Kalkini",
      "Kazibari",
      "Khakdi Bus Stand",
      "Kulpoddi Post Office",
      "Madaripur Bus Terminal",
      "Madaripur Police Station",
      "Madaripur Sadar",
      "Mostafapur",
      "Mostafapur Bus Stand",
      "Panchar",
      "Puran Bazar",
      "Rajoir",
      "Rajoir Khalia",
      "Sahabrampur",
      "Shibchar",
    ],
    "Manikganj-Shibloya": [
      "Shibloya Aricha",
      "Shibloya Shibaloy",
      "Shibloya Tewta",
      "Shibloya Uthli",
    ],
    "Manikganj-Singair": [
      "Singair Baira",
      "Singair Basta Stand",
      "Singair Joymantop",
      "Singair Sadar",
    ],
    "Manikganj-Town": [
      "Baliati",
      "Barangail",
      "Betila",
      "Beutha",
      "Dashora",
      "Dautiya",
      "Gheor",
      "Gilondo",
      "Gorpara",
      "Horirampur",
      "Joyra",
      "Kachari",
      "Mahadebpur",
      "Manikganj Bazar",
      "Manikganj Doulatpur",
      "Manikganj Sadar",
      "Noyadingi",
      "Purra",
      "Rajibpur",
      "Saturia",
      "Seutha",
      "Uchutia",
    ],
    "Munshiganj-Gajaria": [
      "Gajaria Hossendi",
      "Gajaria Rasulpur",
      "Gajaria Sadar",
      "Gazaria Anarpur",
      "Gazaria Char Decree",
      "Gazaria Jamaldi",
      "Gazaria Mirergaon",
    ],
    "Munshiganj-Lohajong": [
      "Lohajong",
      "Lohajong Gouragonj",
      "Lohajong Haldia SO",
      "Lohajong Haridia",
      "Lohajong Haridia DESO",
      "Lohajong Korhati",
      "Lohajong Madini Mandal",
      "Lohajong Medini Mandal EDSO",
      "Louhajang Atigaon",
      "Louhajang Bankhira",
      "Louhajang Dohori",
      "Louhajang Ghurduwr",
      "Louhajang Jhaputia",
      "Louhajang Kahetara",
      "Louhajang Kalma",
      "Louhajang Nagerhat Bazar",
      "Louhajang Pachaldia",
      "Louhajang Satgharia",
      "Louhajang Surpara",
      "Louhajang Vorakor",
    ],
    "Munshiganj-Sirajdikhan": [
      "Sirajdikhan",
      "Sirajdikhan Ichapur",
      "Sirajdikhan Kola",
      "Sirajdikhan Malkha Nagar",
      "Sirajdikhan Shekher Nagar",
    ],
    "Munshiganj-Town": [
      "Adhara",
      "Aparkati",
      "Autshahi",
      "Bagahia Kandi",
      "Baghia",
      "Baghra",
      "Bajrajugini",
      "Bajrozogini",
      "Baligao",
      "Betkahat",
      "Bhaggyakul",
      "Chahida Bazar",
      "Char Masura",
      "Dewbhog Bazar",
      "Dighirpar",
      "Dogachi",
      "Dulihatta",
      "East Shillmandi",
      "Fultola",
      "Gonokpara",
      "Hasail",
      "Hashail Bazar",
      "Hashara",
      "Hatimara",
      "Idrakpur",
    ],
    Narayanganj: [
      "Araihazar",
      "Araihazar Gopaldi",
      "Baidder Bazar",
      "Baidder Bazar Bara Nagar",
      "Baidder Bazar Barodi",
      "Bandar",
      "Bandar BIDS",
      "Bandar D.C Mills",
      "Fatullah",
      "Fatullah Bazar",
      "Madanganj",
      "Narayanganj Sadar",
      "Nobiganj",
      "Rupganj",
      "Rupganj Bhulta",
      "Rupganj Kanchan",
      "Rupganj Murapara",
      "Rupganj Nagri",
      "Siddirganj Adamjeenagar",
      "Siddirganj LN Mills",
      "Siddirganj Siddirganj",
    ],
    Narsingdi: [
      "Basail",
      "Belabo",
      "Bilasdi",
      "Bot-Tola",
      "Brahmondi",
      "Charnagardi",
      "Char Sindhur",
      "Chinishpur",
      "Daspara",
      "Dogoria",
      "Ghorashal",
      "Ghorashal Bazar",
      "Goradia",
      "Grorashal Pran Factory",
      "Grorashal Sarkar Khana",
      "Hazupur",
      "Janata Jute Mile",
      "Kandapara",
      "Karimpur",
      "Kawriapara",
      "Madhabdi",
      "Monohordi",
      "Monohordi Hatirdia",
      "Monohordi Katabaria",
      "Narsingdi Bazar",
    ],
    Nawabganj: ["Bandura", "Joypara", "Khanepur", "Sujapur"],
    "Rajbari-Baliakandi": ["Baliakandi", "Baliakandi Nalia"],
    "Rajbari-Pangsha": [
      "Pangsha Mrigibazar",
      "Pangsha Ramkol",
      "Pangsha Ratandia",
      "Pangsha Sadar",
    ],
    "Rajbari-Townb": [
      "Aladipur",
      "Banibaha",
      "Bank Para",
      "Bash Hata",
      "Beradanga",
      "Bhabanipur",
      "Boro Laxmipur",
      "Choto Bridge Khankhanapur",
      "Dewan Para",
      "Doulodia Ghat",
      "Doulodia Rail Station",
      "Doulodia Sign Board",
      "Doulodia Union Boad",
      "Fire Service Goalanda",
      "Goalanda Hospital",
      "Goalanda Mor",
      "Goalanda Railgate",
      "Jomider Bridge",
      "Kazibadha",
      "Kazikanda",
      "Kenala Ghat",
      "Khanapur Notun Bazar",
      "Khankhanapur",
      "Kollanpur",
      "Lokkhikul",
    ],
    Savar: [
      "Ashulia Paragram",
      "Ashulia Tongabari",
      "Hemayetpur Jainabari",
      "Hemayetpur Shampur",
      "Hemayetpur Tatulzhora Mor",
      "Jahangirnagar University",
      "Kashem Cotton Mills",
      "Rajphulbaria",
      "Savar Akran Bazaar",
      "Savar Amin Bazar",
      "Savar Aralia Bazar Jame Mosjid",
      "Savar Ashulia Stand",
      "Savar Baipayl",
      "Savar Bank Colony",
      "Savar Bank Town",
      "Savar Baroipara",
      "Savar Basp",
      "Savar Boliarpur",
      "Savar Bus Stand",
      "Savar Cantonment",
      "Savar Canttonment",
      "Savar Chakrobarti Stand",
      "Savar Chandra Stand",
      "Savar Chapain Road",
      "Savar Charabag More",
    ],
    "Shariatpur-Naria": [
      "Naria Bhozeshwar",
      "Naria Gharisar",
      "Naria Kartikpur",
      "Naria Sadar",
      "Naria Upshi",
    ],
    "Shariatpur-Town": [
      "Bhedorganj",
      "Damudhya",
      "Dashatta",
      "Dhanuka Police Line",
      "Gosairhat",
      "Jajira",
      "Kagdi Bazar",
      "Palong Bazar",
      "Sakhipur",
      "Shariatpur Sadar",
      "Shariatpur Sadar Angaria",
      "Shariatpur Sadar Chikandi",
      "Tulasar",
    ],
    "Tangail-Basail": ["Bagil", "Basail Bazar", "Basail Sadar"],
    "Tangail-Bhuapur": ["Arjuna", "Bhuapur Sadar", "Nikrail"],
    "Tangail-Deldur": [
      "Delduar Elasin",
      "Delduar Hinga Nagar",
      "Delduar Jangalia",
      "Delduar Lowhati",
      "Delduar Patharail",
      "Delduar Saddar",
    ],
    "Tangail-Dhanbari": ["Baniajan", "Dhanbari Sadar", "Dhopakhali"],
    "Tangail-Ghatail": [
      "Ghatail D. Pakutia",
      "Ghatail Dhalapara",
      "Ghatail Lohani",
      "Ghatail Saddar",
      "Ghatail Zahidganj",
    ],
    "Tangail-Gopalpur": [
      "Gopalpur Chatutia",
      "Gopalpur Hemnagar",
      "Gopalpur Jhowail",
      "Gopalpur Saddar",
    ],
    "Tangail-Kalihati": [
      "Kalihati Ballabazar",
      "Kalihati Elinga",
      "Kalihati Kalihati",
      "Kalihati Nagarbari",
      "Kalihati Nagarbari SO",
      "Kalihati Nagbari",
      "Kalihati Palisha",
      "Kalihati Rajafair",
    ],
    "Tangail-Madhupur": [
      "Ausnara",
      "Madhupur",
      "Madhupur Dhobari",
      "Sholakuri",
    ],
    "Tangail-Mirzapur": [
      "Mirzapur Gorai",
      "Mirzapur Jarmuki",
      "Mirzapur M.C. College",
      "Mirzapur Mohera",
      "Mirzapur Saddar",
      "Mirzapur Warri Paikpara",
    ],
    "Tangail-Nagarpur": [
      "Nagarpur Dhuburia",
      "Nagarpur Sadar",
      "Nagarpur Salimabad",
    ],
    "Tangail-Sakhipur": [
      "Dariapur",
      "Kalmegha",
      "Sakhipur Kochua",
      "Sakhipur Sadar",
    ],
    "Tangail-Town": [
      "Charabari",
      "Elanga",
      "Gala",
      "Jugni Bazar",
      "Kasil",
      "Potol Bazar",
      "Pugli",
      "Rosulpur",
      "Salimpur",
      "Soto Basail",
      "Tangail Sadar",
      "Tangail Sadar Kagmari",
      "Tangail Sadar Karatia",
      "Tangail Sadar Porabari",
      "Tangail Sadar Santosh",
      "Tarotiya",
      "Vaita",
      "Vatkora",
    ],
    Tongi: [
      "27 Bus Stand",
      "Arichpur",
      "Badham",
      "Besic-fokir market",
      "Besic industrial area",
      "Beximco",
      "Bonomala",
      "Boro bari",
      "Cherag Ali",
      "Dewra",
      "Gazipura",
      "International madical",
      "Jhinu market",
      "Mail gate",
      "Mirarbazar",
      "Mirash para",
      "Pagar",
      "Shilmoon",
      "Shinbari",
      "Targach",
      "Tongi bazar",
      "Tongi Bscic",
      "Tongi college gate",
      "Tongi Sadar",
      "Tongi Station Road",
    ],
    Bagerhat: [
      "Bagerhat Feri Ghat",
      "Bagerhat Launch Terminal",
      "Bagerhat Sadar",
      "Barabaria",
      "Bhanganpar Bazar",
      "Chalna Ankorage",
      "Charkulia",
      "Chitalmari",
      "Dariala",
      "Fakirhat",
      "Foylahat",
      "Gourambha",
      "Kachua",
      "Kahalpur",
      "Khardwar",
      "Mansa",
      "Mollahat",
      "Mongla Port",
      "Moniganj",
      "Morrelganj",
      "Nagarkandi",
      "P.C College",
      "Pak Gangni",
      "Rampal",
      "Rangdia",
    ],
    Chuadanga: [
      "Alamdanga",
      "Alukdia",
      "Andulbaria",
      "Chuadanga Boalmari",
      "Chuadanga P.T.I",
      "Chuadanga Sadar",
      "Damurhuda",
      "Darshana",
      "Dingedah",
      "Doulatganj",
      "Doulotdiar",
      "Gaid Ghat",
      "Hardi",
      "Hatikata Mor",
      "Hat Kalugonj",
      "Hazrahati",
      "Hoidarpur",
      "Joforpur",
      "Mominpur",
      "Munshiganj",
      "Nilmoniganj",
      "Nur Nagar",
      "Sath Gari Mor",
      "Sorojganj",
      "Subdia",
    ],
    Jessore: [
      "Abhaynagar",
      "Bagachra",
      "Bagherpara",
      "Basundia",
      "Benapole",
      "Bhugilhat",
      "Chanchra",
      "Chougachha",
      "Churamankathi",
      "Gouranagar",
      "Jadabpur",
      "Jashore Airbach",
      "Jashore Cantonment",
      "Jashore - Noapara",
      "Jashore Sadar",
      "Jashore Upa - Shahar",
      "Jeshore Rajarhat",
      "Jhikargachha",
      "Keshobpur",
      "Monirampur",
      "Rupdia",
      "Sarsa",
    ],
    Jhenaidaha: [
      "Dobila",
      "Ektarpur",
      "Harinakundu",
      "Hat Gopalpur Bazar",
      "Jakaria",
      "Jhenaidah Cadet College",
      "Jhenaidah-Kaliganj",
      "Jhenaidah Sadar",
      "Kangshee",
      "Kotchandpur",
      "Maheshpur",
      "Mayadhorpur Village",
      "Naldanga",
      "Shailakupa",
    ],
    "Khulna-Aliapur": ["Alaipur Sadar", "Belphulia", "Rupsha"],
    "Khulna-Amadee": ["Amadee Sadar"],
    "Khulna-Batiaghat": ["Batiaghat Sadar", "Surkalee"],
    "Khulna-Chalna Bazar": ["Bajua", "Chalna Bazar Sadar", "Dakup", "Nalian"],
    "Khulna-Digalia": [
      "Chandni Mahal",
      "Digalia Sadar",
      "Gazirhat",
      "Ghoshghati",
      "Senhati",
    ],
    "Khulna-Dumuria": ["Chuknagar", "Magurkhali", "Shahpur", "Sorafpur"],
    "Khulna-Paikgachha": ["Kapilmoni", "Paikgachha Sadar"],
    "Khulna-Terokhada": ["Ajogora", "Barasat", "Terokhada Sadar"],
    "Khulna-Town": [
      "Atra Shilpa Area",
      "BIT Khulna",
      "Doulatpur",
      "Jahanabad Cantonment",
      "Khulna G.P.O",
      "Khulna Sadar",
      "Khulna Shipyard",
      "Khulna University",
      "Siramani",
      "Sonali Jute Mills",
    ],
    Kushtia: [
      "Bheramara Bazar",
      "Boro Bazer",
      "BRB Bscic Area",
      "Chorhas",
      "Housing",
      "Islamic University - Kushtia",
      "Khas mathurapur",
      "Khoksa",
      "Kumarkhali",
      "Kumarkhali Bazar",
      "Kushtia Mohini",
      "Kushtia Sadar",
      "Lahini Bot Toil",
      "Mirpur",
      "Mojompur",
      "Mongolbari Bazar",
      "Poradaho Bazer",
      "Singer Mor",
      "Taragunia",
      "Tri-Mohoni Bazar",
    ],
    Magura: ["Magura Sadar", "Mohammadpur", "Shalikha Upazila", "Sreepur Road"],
    Meherpur: [
      "Amjhupi Bazar",
      "Bajitpur Border",
      "Bamun Para",
      "Baribaka",
      "Boro Bazar",
      "Bosepara",
      "Buripota Border",
      "Chadbil Mor",
      "Gangni Bamundi",
      "Gangni Dhankhola",
      "Gangni Harbhanga",
      "Gangni Kasba",
      "Gangni Kumaridanga",
      "Gangni Manikdia",
      "Gangni Nittyanandapur",
      "Gangni Sadar",
      "Gopalpur",
      "Khan Para",
      "Kolar Mor",
      "Kulbaria Bazar",
      "Meherpur Bandar",
      "Meherpur Bus Stand Para",
      "Meherpur College Mor",
      "Meherpur Ghosh Para",
      "Meherpur Hospital Gate",
    ],
    Narail: [
      "Adompur",
      "Aladatpur",
      "Awuriya",
      "Badha Ghat Mor",
      "Balarampur",
      "Baradia",
      "Bashgram Bazar",
      "Bharashula",
      "Bhawakhali",
      "Bishnupur",
      "Bolorampur",
      "Chamroli",
      "Circuit House Area",
      "Dokkhin Narail",
      "Doljitpur",
      "Dumurtola",
      "Durvazury",
      "Ghorakhali Bazar",
      "Ghorakhali Mor",
      "Gobra Bazar",
      "Gochar",
      "Habakhali",
      "Harigara Bajar",
      "Hatbariya",
      "Hobokhali",
    ],
    Satkhira: [
      "Assasuni",
      "Baikari Union",
      "Bhomra Union",
      "Budhhat",
      "Buri Goalini",
      "Chanduria",
      "Debhata",
      "Dhulihar",
      "Gabura",
      "Ghona",
      "Jhaudanga",
      "Kalaroa",
      "Kuskhali",
      "Nalta Mubaroknagar",
      "Noornagar",
      "Patkelghata",
      "Ratanpur",
      "Satkhira Islamia Acc",
      "Satkhira Kaliganj",
      "Satkhira Sadar",
      "Shyamnagar",
      "Taala",
    ],
    "Jamalpur-Dewangonj": ["Dewangonj Dewangonj S. Mills", "Dewangonj Sadar"],
    "Jamalpur-Islampur": [
      "Islampur Durmoot",
      "Islampur Gilabari",
      "Islampur Sadar",
    ],
    "Jamalpur-Madarganj": ["Madarganj Balijhuri", "Madarganj Sadar"],
    "Jamalpur-Malandah": [
      "Malandah Jamalpur",
      "Malandah Mahmoodpur",
      "Malandah Malancha",
      "Malandah Sadar",
    ],
    "Jamalpur-Shorishbari": [
      "Madarganj Adarvita",
      "Shorishabari Bausee",
      "Shorishabari Jagannath Ghat",
      "Shorishabari Jamuna Sar Karkhana",
      "Shorishabari Pingna",
      "Shorishabari Shorishabari",
    ],
    "Jamalpur-Town": [
      "Beltia",
      "Bhabki",
      "Charpolisha",
      "Jamalpur Bus Terminal",
      "Jamalpur Court",
      "Jamalpur Nandina",
      "Jamalpur Narundi",
      "Jamalpur Railway Station",
      "Jamalpur Sadar",
      "Jamalpur Shantinagar",
      "Khoshmahal",
      "Shekhervita",
      "Shihata",
    ],
    "Mymensingh-Gaforgaon": [
      "Gaforgaon Duttarbazar",
      "Gaforgaon Kandipara",
      "Gaforgaon Sadar",
      "Gaforgaon Shibganj",
      "Gaforgaon Usti",
    ],
    "Mymensingh-Gouripur": ["Gouripur Ramgopalpur", "Gouripur Sadar"],
    "Mymensingh-Haluaghat": [
      "Haluaghat Dhara",
      "Haluaghat Munshirhat",
      "Haluaghat Sadar",
    ],
    "Mymensingh-Isshwargonj": [
      "Isshwargonj Atharabari",
      "Isshwargonj Isshwargonj",
      "Isshwargonj Sohagi",
    ],
    "Mymensingh-Muktagacha": ["Bahenga", "Muktagachha Sadar", "Palgaon"],
    "Mymensingh-Nandail": ["Nandail Gangail", "Nandail Sadar"],
    "Mymensingh-Phulpur": [
      "Phulpur Beltia",
      "Phulpur Phulpur",
      "Phulpur Tarakanda",
    ],
    "Mymensingh-Town": [
      "Akua",
      "Bhaluka",
      "C.K. Gosh Road",
      "Chorpara Area",
      "Fulbaria Asim",
      "Maskanda Bypass",
      "Mymensingh Sadar",
      "Mymensingh Sadar Agriculture Universi",
      "Mymensingh Sadar Biddyaganj",
      "Mymensingh Sadar Kawatkhali",
      "Mymensingh Sadar Shombhuganj",
      "Mymensingh Zero Point",
      "Rahamatpur Engineering College",
      "Sankipara Jamtola Ses More",
      "Tarakanda Bazar",
      "Trishal Kabi Nazrul University",
    ],
    "Mymensingh-Trishal": [
      "Trishal Ahmadbad",
      "Trishal Dhala",
      "Trishal Ram Amritaganj",
      "Trishal Saddar",
    ],
    Netrokona: [
      "Atpara",
      "Barhatta",
      "Dharmapasha",
      "Dhobaura",
      "Kalmakanda",
      "Kendua",
      "Khaliajuri Saddar",
      "Khaliajuri Shaldigha",
      "Madan Madan",
      "Moddhynagar Moddoynagar",
      "Mohanganj",
      "Netrakona Sadar",
      "Netrakona Sadar Baikherhati",
      "Pachkahonia",
      "Purbadhola Jaria Jhanjhail",
      "Purbadhola Saddar",
      "Purbadhola Shamgonj",
      "Susung Durgapur",
    ],
    Sherpur: [
      "Akheri Bazar",
      "Astomi Tola",
      "Bakshigonj Bakshigonj",
      "Bazit Khila",
      "Boira Puran Pur",
      "Chakpathak",
      "Chapatoli",
      "Dhakolhati",
      "Durga Narayan Pur",
      "Garial Bari",
      "Gouripur",
      "Gowalpotti",
      "Gridda Narayanpur",
      "Jhinaigati",
      "Khowarpar",
      "Kushum Hati",
      "Methor Potti",
      "Moddho Sheri",
      "Nabaron School",
      "Nakla",
      "Nakla Gonopaddi",
      "Nalitabari",
      "Nalitabari Hatibandha",
      "Nayanibazar",
      "Nazira Bag Bazar",
    ],
    Bogura: [
      "Adamdighi",
      "Bagura Cantonment",
      "Bagura Sadar",
      "Balkuchi",
      "Balukapara",
      "Barachapra",
      "Bhatkandi",
      "Bottola Bazar",
      "Chalapara",
      "Champapur",
      "Chandaikona",
      "Chandan Baisha",
      "Chhantiagram",
      "Debkhanda",
      "Dhunat",
      "Dupchachia",
      "Erulia",
      "Gabtoli",
      "Gokul",
      "Gosaibari",
      "Goshaibari",
      "Kahaloo",
      "Kahalu",
      "Khanpur",
      "Kundagram",
    ],
    "Chapai Nawabganj": [
      "Amnura",
      "Bholahat",
      "Chapai Nawabganj Sadar",
      "Char Bagdanga",
      "Debinagar",
      "Gobratola",
      "Gomashtapur",
      "Kansart",
      "Manaksha",
      "Mandumala",
      "Moharajpur",
      "Nachol",
      "Rajarampur",
      "Ramchandrapur",
      "Rohanpur",
      "Shahibag",
      "Shibganj U.P.O",
    ],
    Joypurhat: [
      "Akklepur",
      "Amdai",
      "Bhadsha Union",
      "Dhalahar",
      "Jamalganj Bazar",
      "Joypurhat Municipality Office",
      "Joypurhat Sadar",
      "Joypurhat Stadium",
      "Kalai",
      "Khetlal",
      "Mongolbari",
      "Panchbibi",
      "Puranapail",
      "Tilakpur",
    ],
    Naogaon: [
      "Ahsanganj",
      "Badalgachhi",
      "Balihar",
      "Baludanga",
      "Bandai",
      "Dhamuirhat",
      "Dubalhati",
      "Ganguria",
      "Hashaighari",
      "Kashimpur Bazar",
      "Mahadevpur",
      "Manda",
      "Moduhil",
      "Naogaon Sadar",
      "Niamatpur",
      "Nitpur",
      "Patnitala",
      "Porsa",
      "Prasadpur",
      "Raninagar",
      "Sailgachhi",
      "Sapahar",
    ],
    Natore: [
      "Abdulpur",
      "Baiddyabal Gharia",
      "Baraigram",
      "Dattapara Bazar",
      "Dayarampur",
      "Digapatia",
      "Gopalpur U.P.O",
      "Harua",
      "Hatgurudaspur",
      "Lalpur S.O",
      "Laxman",
      "Madhnagar",
      "Natore Sadar",
      "Singra",
    ],
    Pabna: [
      "Banwarinagar",
      "Bera",
      "Bhangura",
      "Chatmohar",
      "Dashuria",
      "Debottar",
      "Dhapari",
      "Hamayetpur",
      "Ishwardi",
      "Kaliko Cotton Mills",
      "Kashinathpur",
      "Nakalia",
      "Pabna Sadar",
      "Pakshi",
      "Puran Bharenga",
      "Rajapur Bus Station",
      "Ruppur",
      "Sagarkandi",
      "Sathia",
      "Sujanagar",
    ],
    Rajshahi: [
      "Arani",
      "Bagha",
      "Bhabaniganj",
      "Binodpur Bazar",
      "Charghat",
      "Durgapur",
      "Ghoramara",
      "Godagari",
      "Katakhali",
      "Kazla",
      "Koyel",
      "Lalitganj",
      "Nowhata",
      "Premtoli",
      "Putia",
      "Rajshahi Cantonment",
      "Rajshahi Court",
      "Rajshahi - Mohanpur",
      "Rajshahi Sadar",
      "Rajshahi Sugar Mills",
      "Rajshahi University",
      "Sapura",
      "Sardah",
      "Shyampur",
      "Taherpur",
    ],
    Sirajganj: [
      "Baiddya Jam Toil",
      "Belkuchi",
      "Dhangora",
      "Enayetpur",
      "Gandail",
      "Jamirta",
      "Kaijuri",
      "Kazipur",
      "Lahiri Mohanpur",
      "Makimpur",
      "Malonga",
      "Porjana",
      "Raipur Station Playground",
      "Rashidabad",
      "Salap",
      "Shahjadpur",
      "Shuvgachha",
      "Sirajganj Sadar",
      "Sohagpur",
      "Tarash",
      "Ullapara",
      "Ullapara R.S",
    ],
    Dinajpur: [
      "Ansar Club",
      "Asrom Para",
      "Bahadur Bazar",
      "Basuniya Potti",
      "BGB Camp",
      "Birampur - Birampur",
      "Birganj - Golapganj",
      "Birganj - Kobiraj Hat",
      "Birol",
      "Birol Bazar",
      "Birol - Monggolpur",
      "BKSP",
      "Bochaganj - Bochaganj",
      "Bochaganj - Setabganj",
      "Boro Gurgola",
      "Boromath",
      "Botibabur Mor",
      "Bottoli Bazar",
      "Bottoli Mor",
      "Brac Center",
      "Brtc Road",
      "Chak Banarasi",
      "Charubabur More",
      "Chawliya Potti",
      "Chehelgazi School",
    ],
    Gaibandha: [
      "Fulchhari - Balashi Ghat",
      "Fulchhari - Fulchari Konchi Para",
      "Gaibandha Sadar - Badiakhali",
      "Gaibandha Sadar - Bara Gayaspur",
      "Gaibandha Sadar - Gaibandha Sadar",
      "Gaibandha Sadar - Indira Par",
      "Gaibandha Sadar - Kumarpara",
      "Gaibandha Sadar - Kuptola",
      "Gaibandha Sadar - Masterpara",
      "Gaibandha Sadar - Modhdhopara",
      "Gaibandha Sadar - Mondolpara",
      "Gaibandha Sadar - Polash Para",
      "Gobindaganj Baluyapara",
      "Gobindaganj - Kanipara",
      "Gobindaganj Mollapara",
      "Gobindoganj",
      "Palashbari - Ambari",
      "Palashbari - Baghjana",
      "Palashbari - Bisramgachi",
      "Palashbari - Jalinge",
      "Palashbari - Palashbari",
      "Palashbari - Suigram",
      "Sadullapur",
      "Sadullapur - Jugibai",
      "Sadullapur Naldanga Union",
    ],
    Kurigram: [
      "Bhogdanga",
      "Bhurungamari",
      "Char Rajibpur",
      "Chilmari",
      "Jatrapur",
      "Kurigram Phulbari",
      "Kurigram Rajarhat",
      "Kurigram Sadar",
      "Nageshwari",
      "Panchgachi",
      "Rangalirbash",
      "Rowmari",
      "Ulipur",
    ],
    Lalmonirhat: [
      "Aditmari Bhelabari",
      "Aditmari Durgapur",
      "Aditmari Kamlabari",
      "Aditmari Kashiabarir Hat",
      "Aditmari Mohiskhocha",
      "Aditmari Polashi",
      "Aditmari Saptipari Bazar",
      "Aditmari Sarpukur",
      "Aditmari Upazila Parishad",
      "Balatari Jame Mashjid Lalmonirhat",
      "Barabari",
      "Circuit House Lalmonirhat",
      "Hatibandha Barakhata",
      "Hatibandha Dauabari",
      "Hatibandha Goddimari",
      "Hatibandha Gotamari",
      "Hatibandha Shinduna",
      "Kaliganj Bhotmari",
      "Kaliganj Chandrapur",
      "Kaliganj Dalagram",
      "Kaliganj Gorol",
      "Kaliganj Kakina",
      "Kaliganj Modati",
      "Kaliganj Tushvandar",
      "Kaliganj Vullar Hat",
    ],
    Nilphamari: [
      "Badia'r Mor",
      "Chowrongi Mor",
      "Circuit House Mor",
      "College Station",
      "Dimla Balapara",
      "Dimla Gayabari",
      "Dimla Khoga Khoribari",
      "Dimla Nautara",
      "Dimla Paschim Chatnai",
      "Dimla Sadar",
      "Dimla Shothibari Bazar",
      "Domar Boragari Bazar",
      "Domar Gomnati Bazar",
      "Domar Halhalia",
      "Domar Sonaray Bazar",
      "Domar Thana",
      "Harowa",
      "Jaldhaka",
      "Kalitola",
      "Kishoreganj Check Post Bazar",
      "Kishoreganj Kalikapur",
      "Maniker Mor",
      "Nilphamari - Gobindopur",
      "Niphamari Kishoreganj Sadar",
      "Notkhana",
    ],
    "Nilphamari-Saidpur": [
      "Bangalipur",
      "Cant Bazar",
      "Golahat Railway Colony",
      "Hati Kahana",
      "Kashiram Belpukur",
      "Kundol",
      "Nilphamari Sadar",
      "Saidpur Airport",
      "Saidpur Bus Terminal",
      "Saidpur Lakshmanpur",
      "Saidpur Pach Matha Mor",
      "Saidpur Plaza",
      "Saidpur Post Office",
      "Saidpur Railway Station",
      "Saidpur Super Market",
      "Wapda Bazar",
    ],
    Panchagarh: [
      "Atwari",
      "Boda Banagram",
      "Boda Haldibari",
      "Boda Maidandighi",
      "Bp Government High School Hostel Panchagarh",
      "Debigang Thana",
      "Debiganj Dhuajhari Bazar",
      "Debiganj Kaharganj",
      "Docropara",
      "Nimnagar Mosque Panchagarh",
      "Panchagarh Sadar",
      "Tetulia",
    ],
    Rangpur: [
      "Adarsopara",
      "Alamnagar Road",
      "Ansari Mor",
      "Arshad Nagor",
      "Asrotpur",
      "Babukha",
      "Badarganj",
      "Badarganj Sahidminar",
      "Bangladesh Bank Mor",
      "Barabil Gangachara",
      "Beacon Mor",
      "Betpotti",
      "Birganj",
      "Boiragi Para",
      "Bokultola",
      "Borobari",
      "Boubazar",
      "Burirhat",
      "C.M.B Quarter",
      "C.O Bazar",
      "Central Road",
      "Charokbari",
      "Chartola Mor",
      "Chatra",
      "Checkpost 3 Numbar",
    ],
    Thakurgaon: [
      "BADC Staff Quarter",
      "Baliadangi",
      "Baliadangi Ruhia",
      "Border Guard Bangladesh",
      "College Para",
      "Goalpara",
      "Gobindo Nogor Mondir Para",
      "Goreya",
      "Goshpara",
      "Hazipara",
      "Islambag",
      "Jamidarpara",
      "Kalitola Bazar",
      "Khalpara",
      "Nishchintapur",
      "Ranisankail Durlovpur",
      "Ranisankail Mirdangi",
      "Ranisankail Rajbari",
      "Sarakar Para",
      "Thakurgaon - Haripur",
      "Thakurgaon - Munshipara",
      "Thakurgaon - Pirganj",
      "Thakurgaon Sadar",
      "Thakurgaon - Tatipara",
    ],
    Habiganj: [
      "Azmireeganj",
      "Bahubal",
      "Baniachang",
      "Baniachang Jatrapasha",
      "Baniachang Kadirganj",
      "Chunarughat",
      "Chunarughat Chandpurbagan",
      "Chunarughat Narapati",
      "Habiganj Sadar",
      "Habiganj Sadar Gopaya",
      "Habiganj Sadar Shaestaganj",
      "Madhabpur",
      "Madhabpur Itakhola",
      "Madhabpur Saihamnagar",
      "Madhabpur Shahajibazar",
      "Nabiganj",
      "Nabiganj Digalbak",
      "Nabiganj Golduba",
      "Nabiganj Goplarbazar",
      "Nabiganj Inathganj",
      "Shaestaganj Gonganagar",
      "Sheaestaganj Shankhola Bazar",
    ],
    Moulvibazar: [
      "Akhailkura",
      "Bahar Mordan",
      "Banani",
      "Baralekha Baralekha",
      "Baralekha Dhakkhinbag",
      "Baralekha Juri",
      "Baralekha Purbashahabajpur",
      "Baronti",
      "Bhairabganj Bazar",
      "Borhat",
      "Borshijura",
      "Boruna",
      "Buddhimontopur",
      "Damia",
      "Dighirpar - Moulvibazar",
      "Durlovpur",
      "Ekatuna",
      "Ghumra",
      "Giasnagar",
      "Gobindopur",
      "Gujarai",
      "Hilalpur",
      "Jagatshi",
      "Jogonnathpur",
      "Jugidor",
      "Kadamhata",
    ],
    Sunamganj: [
      "Bishwamvarpur",
      "Chhatak",
      "Chhatak Cement Factory",
      "Chhatak Chourangi Bazar",
      "Chhatak Gabindaganj",
      "Chhatak Gabindaganj Natun Bazar",
      "Chhatak Islamabad",
      "Chhatak jahidpur",
      "Chhatak Khurma",
      "Chhatak Moinpur",
      "Chhatak Paper Mills",
      "Derai Chandpur",
      "Derai Sadar",
      "Dowarabazar",
      "Ghungiar",
      "Jagannathpur Sadar",
      "Jagnnathpur Atuajan",
      "Jagnnathpur Hasan Fatemapur",
      "Jagnnathpur Rasulganj",
      "Jagnnathpur Shiramsi",
      "Jagnnathpur Syedpur",
      "Jamalganj",
      "Rangarchar",
      "Sachna",
      "Selborash",
    ],
    "Sylhet-Balaganj": [
      "Balaganj Begumpur",
      "Balaganj Brahman Shashon",
      "Balaganj Gaharpur",
      "Balaganj Goala Bazar",
      "Balaganj Karua",
      "Balaganj Kathal Khair",
      "Balaganj Natun Bazar",
      "Balaganj Omarpur",
      "Balaganj Sadar",
      "Balaganj Tajpur",
    ],
    "Sylhet-Bianibazar": [
      "Beanibazar Beanibazar",
      "Beanibazar Churkai",
      "Beanibazar jaldup",
      "Beanibazar Kurar bazar",
      "Beanibazar Mathiura",
      "Bianibazar Salia bazar",
    ],
    "Sylhet-Bishwanath": [
      "Bishwanath Bishwanath",
      "Bishwanath Dashghar",
      "Bishwanath Deokalas",
      "Bishwanath Doulathpur",
      "Bishwanath Singer kanch",
    ],
    "Sylhet-Fenchuganj": [
      "Dowbangla",
      "Fenchuganj Fenchuganj",
      "Fenchuganj Fenchuganj SareKarkh",
    ],
    "Sylhet-Goainhat": [
      "Goainhat Chiknagul",
      "Goainhat Goainhat",
      "Goainhat Jaflong",
    ],
    "Sylhet-Golapganj": [
      "Banigram",
      "Bhadeshwar",
      "Budhbari Bazar",
      "Dhaka Dakkhin",
      "Golapganj Sadar",
      "Jalalpur",
      "Kotalpur",
      "Ranaping Bazar",
      "Shekhpur",
      "West Barokut",
    ],
    "Sylhet-Jakiganj": [
      "Zakiganj Bazar",
      "Zakiganj Ichhamati",
      "Zakiganj Sadar",
    ],
    "Sylhet-Kanaighat": [
      "Kanaighat Chatulbazar",
      "Kanaighat Sadar",
      "Lakhsmi Prasad",
      "Rajaganj",
    ],
    "Sylhet Sadar": [
      "Akhalia",
      "Alampur",
      "Ambarkhana",
      "Badam Bagicha",
      "Baghibari",
      "Bhatalia",
      "Bil Par",
      "Bimanbondarair Road",
      "Boroikandi",
      "Charadigirpar",
      "Chondan Tula",
      "Choukidighi",
      "Daptari Para",
      "Dargah Mahalla",
      "Darjee Band",
      "Dattapara",
      "Gasitula",
      "Golapganj",
      "Haripur",
      "Hatimbagh",
      "Hauldar Para",
      "Hawapara",
      "Jalalabad",
      "Jalalabad Cantonment",
      "Jamtala",
    ],
  };

  // Watch mode mendatory for live changing of some form values
  const [divisionValue, cityValue] = watch([
    "division",
    "city",
    "area",
    "deliveryOption",
  ]);

  useEffect(() => {
    setValue("division", divisionValue);
    setValue("city", ""); // Reset city value when division changes
    setValue("area", ""); // Reset area value when division changes
  }, [divisionValue, setValue]);

  useEffect(() => {
    setValue("area", ""); // Reset area value when division changes
  }, [cityValue, setValue]);

  const handleTagButton = (value: string) => {
    setValue("deliveryOption", value);
  };

  return (
    <Box className={styles.address}>
      <Grid container mb={4}>
        <Grid item xs={12} md={6}>
          <Box className={styles.address__leftItem}>
            <Box className={styles.address__inputItem}>
              <label className={styles.address__inputLabel} htmlFor="name">
                Full Name *
              </label>
              <input
                id={"name"}
                type="text"
                placeholder="Input full name"
                className={styles.address__input}
                {...register("fullName", { required: "Your name is required" })}
              />
              {errors.fullName && (
                <Typography
                  component={"span"}
                  className={styles.address__errorMsg}
                >
                  {errors.fullName.message}
                </Typography>
              )}
            </Box>

            <Box className={styles.address__inputItem}>
              <label className={styles.address__inputLabel} htmlFor="number">
                Mobile Number *
              </label>
              <input
                id={"number"}
                type="number"
                placeholder="Input mobile number"
                className={styles.address__input}
                {...register("phone", {
                  required: "Please provide a valid phone number",
                  minLength: {
                    value: 10,
                    message: "Phone number must be at least 10 digits long",
                  },
                })}
              />
              {errors.phone && (
                <Typography
                  component={"span"}
                  className={styles.address__errorMsg}
                >
                  {errors.phone.message}
                </Typography>
              )}
            </Box>

            <Box className={styles.address__inputItem}>
              <label
                style={{ marginBottom: "8px" }}
                className={styles.address__inputLabel}
                htmlFor="division"
              >
                Division *
              </label>
              <SelectBox
                value={getValues("division")}
                options={divisions.map((division) => division.name)}
                label="Please choose your division"
                register={register("division", {
                  required: "Please provide your division",
                })}
                sx={{ width: "100%!important" }}
              />
              {errors.division && (
                <Typography
                  component={"span"}
                  className={styles.address__errorMsg}
                >
                  {errors.division.message}
                </Typography>
              )}
            </Box>

            <Box className={styles.address__inputItem}>
              <label
                style={{ marginBottom: "8px" }}
                className={styles.address__inputLabel}
                htmlFor="city"
              >
                City *
              </label>
              <SelectBox
                value={getValues("city")}
                options={
                  divisionValue
                    ? divisions.find(
                        (division) => division.name === divisionValue
                      )?.cities || []
                    : []
                }
                label="Please choose your city"
                register={register("city", {
                  required: "Please provide your city",
                })}
                sx={{ width: "100%!important" }}
                disabled={!divisionValue}
              />
              {errors.city && (
                <Typography
                  component={"span"}
                  className={styles.address__errorMsg}
                >
                  {errors.city.message}
                </Typography>
              )}
            </Box>

            <Box className={styles.address__inputItem}>
              <label
                style={{ marginBottom: "8px" }}
                className={styles.address__inputLabel}
                htmlFor="area"
              >
                Area *
              </label>
              <SelectBox
                value={getValues("area")}
                options={cityValue ? areas[cityValue] || [] : []}
                label="Please choose your area"
                register={register("area", {
                  required: "Please provide your area",
                })}
                sx={{ width: "100%!important" }}
                disabled={!cityValue}
              />
              {errors.area && (
                <Typography
                  component={"span"}
                  className={styles.address__errorMsg}
                >
                  {errors.area.message}
                </Typography>
              )}
            </Box>
          </Box>
        </Grid>
        <Grid item xs={12} md={6}>
          <Box className={styles.address__rightItem}>
            {/* Address Field */}
            <Box className={styles.address__inputItem}>
              <label className={styles.address__inputLabel} htmlFor="address">
                Address *
              </label>
              <input
                id={"address"}
                type="text"
                placeholder="House no. / building / street / area"
                className={styles.address__input}
                {...register("address", { required: "Provide your address" })}
              />
              {errors.address && (
                <Typography
                  component={"span"}
                  className={styles.address__errorMsg}
                >
                  {errors.address.message}
                </Typography>
              )}
            </Box>

            {/* LandMark Field */}
            <Box className={styles.address__inputItem}>
              <label className={styles.address__inputLabel} htmlFor="landmark">
                Landmark {"(Optional)"}
              </label>
              <input
                id={"landmark"}
                type="text"
                placeholder="E.g. beside train station"
                className={styles.address__input}
                {...register("landmark")}
              />
            </Box>

            {/* Delivery option */}
            <Box className={styles.address__inputItem}>
              <label
                className={styles.address__inputLabel}
                htmlFor="deliveryOption"
                style={{ marginBottom: "8px" }}
              >
                Select a label for effective delivery:
              </label>
              <Box>
                <TagButton
                  onClick={() => handleTagButton("home")}
                  label="Home"
                  register={register("deliveryOption")}
                  sx={{
                    padding: "10px 30px!important",
                    borderRadius: "4px!important",
                    marginRight: "15px",
                    border:
                      getValues("deliveryOption") === "home"
                        ? "2px solid #00b207"
                        : "none",
                    "&:hover": {
                      backgroundColor: "#e6e6e6!important",
                      color: "#1a1a1a!important",
                    },
                  }}
                />
                <TagButton
                  onClick={() => handleTagButton("office")}
                  label="Office"
                  register={register("deliveryOption")}
                  sx={{
                    padding: "10px 30px!important",
                    borderRadius: "4px!important",
                    border:
                      getValues("deliveryOption") === "office"
                        ? "2px solid #00b207"
                        : "none",
                    "&:hover": {
                      backgroundColor: "#e6e6e6!important",
                      color: "#1a1a1a!important",
                    },
                  }}
                />
              </Box>
            </Box>
          </Box>
        </Grid>
      </Grid>
      {/* <Box width={"300px"} ml={"auto"} bgcolor={"red"}> */}
      <Button
        text="Save"
        sx={{
          padding: "8px 60px!important",
          marginLeft: "auto",
          display: "flex",
          borderRadius: "8px!important",
        }}
        onClick={handleSubmit(handleAddressData)}
      />
      <ToasterMsg />
    </Box>
  );
};

export default AddressForm;
